### ISSUE TITLE
Fail on fresh install of ubuntu 18.10

### ISSUE THREAD

**Issue by jmramos02** [rstacruz/grub-theme-bandersnatch#1]
I tried running this on a fresh installation of ubuntu 18.10, copying fails as the `themes` folder on `/boot/grub/` doesn't exist yet. after creating the folder, all runs well after :100: 

would it be better if we add a `mkdir` before cp if the `themes` folder doesn't exist yet?

**Comment by rstacruz** [comment]
Hmm... that makes sense. Let's try it. Thanks!
